
services:
  protecao-contra-injecoes:
    build:
      context: ./Protecao_Contra_Injecoes
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - projetos-net

  protecao-contra-sql-injection:
    build:
      context: ./Protecao_Contra_SQL_Injection
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - db
    networks:
      - projetos-net
  
  protecao-idor:
    build:
      context: ./Protecao_IDOR
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - db
    networks:
      - projetos-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ifsp
      MYSQL_DATABASE: sesc7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - projetos-net

volumes:
  db_data:

networks:
  projetos-net:
    driver: bridge

