
services:
  protecao-contra-injecoes:
    build:
      context: ./Protecao_Contra_Injecoes
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - projetos-net

  protecao-contra-sql-injection:
    build:
      context: ./Protecao_Contra_SQL_Injection
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - projetos-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: sesc7
      MYSQL_PASSWORD: ifsp
    command: --bind-address=0.0.0.0
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PWD: ifsp
      DB_NAME: sesc7
    depends_on:
      - db
    networks:
      - backend

networks:
  projetos-net:
    driver: bridge
  backend:
    driver: bridge
